/* Creación de usuarios si está trabajando con BD Oracle Cloud */
CREATE USER AINTEGRAEDI IDENTIFIED BY "DuocUC..2025"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER AINTEGRAEDI QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO AINTEGRAEDI;
GRANT "RESOURCE" TO AINTEGRAEDI;
ALTER USER AINTEGRAEDI DEFAULT ROLE "RESOURCE";

